### ISSUE TITLE
Unnecessary samples are considered when concatenating sequences

### ISSUE THREAD

**Issue by beorostica** [JuliaHealth/KomaMRI.jl#205] opened 2023-10-25 21:01 UTC
When concatenating sequences, sometimes there are samples that shouldn't be regarded when there are zero time distance between extreme samples of two consecutive blocks in a sequence. 

Here is a pulseq 1.4.1 [writeTrufi.m](https://github.com/pulseq/pulseq/blob/master/matlab/demoSeq/writeTrufi.m) example that shows this behaviour:

![image](https://github.com/cncastillo/KomaMRI.jl/assets/36004160/4d9cf504-5b08-4e1b-b92b-0dae71f3d58f)

Has you can see, the green a blue gradients goes to zero an continues a ramp waveform. The actual behavior is due to the definition of waveforms that always starts and ends with zero amplitude. This can be solved in a posterior postprocess of the signals in the sequence.

**Comment by cncastillo** [comment] 2023-11-15 17:14
I don't think this has any impact in the simulation, is just a visual thing for the plots right?

**Comment by beorostica** [comment] 2023-11-23 12:30
Indeed, it has no impact on the simulation.

**Comment by cncastillo** [comment] 2024-03-11 11:35
Duplicate of #320.

**Closed by cncastillo** 2024-03-11 11:35 UTC
Labels: 3) low priority
